sources:
  - name: cars
    handler:
      graphql:
        endpoint: http://localhost:4001/graphql
  - name: users
    handler:
      postgraphile:
        connectionString: postgres://postgres:docker@localhost:5431/users
