# Use postgres/docker user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: mesh-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: users
    ports:
      - 5431:5432
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
